<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UEExplorerRoot Condition="'$(UEExplorerRoot)' == ''">..\..\..\UE-Explorer</UEExplorerRoot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Eliot.UELib">
      <HintPath>$(UEExplorerRoot)\Eliot.UELib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Eliot.Utilities">
      <HintPath>$(UEExplorerRoot)\Eliot.Utilities.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
